#!/usr/bin/env python3
"""
Empirically verify that driver torque scales linearly with the commanded
steering angle vs actual wheel angle gap on the Volvo CMA platform.

Hypothesis
----------
The EPS applies torque proportional to (commanded - actual) angle. When the
driver blocks the wheel at a fixed position while openpilot commands a
progressively larger angle, the driver torque required to hold the wheel
should rise linearly with the gap. If confirmed, this validates the design
of the MAX_ERR_DEG cap in carcontroller.py: capping the gap at N degrees
caps the driver's fight-torque at k * N Nm.

Procedure
---------
Runs at standstill with the brake firmly pressed. The driver grips the wheel
at its resting position (roughly 0 degrees) and holds it through the whole
test. The script cycles apply_angle through a set of values via
live_testing.txt. At each step, it waits for driver torque to stabilise,
records the mean torque and actual wheel angle, then moves on.

A linear regression of torque vs (commanded - actual) gap produces the
Nm-per-degree slope and an R-squared goodness-of-fit number.

Usage
-----
  python calibrate_torque_vs_angle.py
  python calibrate_torque_vs_angle.py --steps 0 5 10 15 0

Safety
------
  - Vehicle MUST be stationary, brake on, gear in P or N.
  - Openpilot must be engaged with lateral active before starting.
  - Driver MUST hold the wheel firmly throughout the test.
  - The script aborts if driver torque exceeds MAX_DRIVER_TORQUE_NM.
  - Ctrl-C at any time restores lat_active=False in live_testing.txt.
"""

import argparse
import signal
import statistics
import sys
import time
from pathlib import Path

OPENPILOT_PATH = Path(__file__).resolve().parents[5]
if str(OPENPILOT_PATH) not in sys.path:
  sys.path.insert(0, str(OPENPILOT_PATH))

import cereal.messaging as messaging

LIVE_TESTING_FILE = "/data/openpilot/live_testing.txt"
LOG_FILE = "/data/openpilot/torque_vs_angle_calibration.csv"

# Settling detection on driver torque
SETTLE_WINDOW = 20             # samples in the rolling window (20 @ 20 Hz = 1 s)
SETTLE_STD_THRESHOLD_NM = 0.8  # Nm; below this the torque is considered stable
SETTLE_TIMEOUT_S = 10.0
SAMPLE_INTERVAL_S = 0.05       # 20 Hz

# After settling, average this many samples for the final reading
FINAL_SAMPLE_COUNT = 40        # 2 s at 20 Hz

# Safety
MAX_DRIVER_TORQUE_NM = 25.0    # abort if driver torque magnitude exceeds this


class TorqueVsAngleCalibrator:
  def __init__(self, steps: list[float]):
    self.steps = steps
    self.results: list[dict] = []
    self.running = True
    self.sm: messaging.SubMaster | None = None
    signal.signal(signal.SIGINT, self._signal_handler)
    signal.signal(signal.SIGTERM, self._signal_handler)

  def _signal_handler(self, sig, frame):
    print("\nInterrupted. Disabling live_testing and exiting...")
    self.running = False
    self._disable_live_testing()
    sys.exit(0)

  def _write_live_testing(self, apply_angle: float) -> None:
    lines = [
      "# Auto-generated by calibrate_torque_vs_angle.py",
      "lat_active=True",
      f"apply_angle={apply_angle}",
    ]
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write('\n'.join(lines) + '\n')

  def _disable_live_testing(self) -> None:
    try:
      with open(LIVE_TESTING_FILE, 'w') as f:
        f.write("# Auto-generated by calibrate_torque_vs_angle.py\nlat_active=False\n")
      print("live_testing disabled (lat_active=False)")
    except Exception as e:
      print(f"WARNING: could not write {LIVE_TESTING_FILE}: {e}")

  def _read_state(self) -> tuple[float | None, float | None]:
    """Return (driver_torque_Nm, steering_angle_deg) or (None, None)."""
    assert self.sm is not None
    self.sm.update(timeout=1000)
    if self.sm.updated['carState']:
      cs = self.sm['carState']
      return cs.steeringTorque, cs.steeringAngleDeg
    return None, None

  def _wait_for_torque_settle(self) -> bool:
    """Wait until rolling std of driver torque drops below SETTLE_STD_THRESHOLD_NM."""
    torques: list[float] = []
    start = time.time()
    while self.running:
      if time.time() - start > SETTLE_TIMEOUT_S:
        print(f"  WARNING: torque did not settle in {SETTLE_TIMEOUT_S}s")
        return False

      tq, _ = self._read_state()
      if tq is None:
        continue

      if abs(tq) > MAX_DRIVER_TORQUE_NM:
        print(f"  SAFETY: driver torque {tq:+.1f} Nm exceeds limit. Aborting.")
        self.running = False
        return False

      torques.append(tq)
      if len(torques) > SETTLE_WINDOW:
        torques.pop(0)

      if len(torques) >= SETTLE_WINDOW:
        std = statistics.stdev(torques)
        if std < SETTLE_STD_THRESHOLD_NM:
          mean = statistics.mean(torques)
          print(f"  settled in {time.time() - start:4.1f}s: "
                f"mean_tq={mean:+.2f} Nm  std={std:.2f} Nm")
          return True

      time.sleep(SAMPLE_INTERVAL_S)
    return False

  def _collect_samples(self, n: int) -> tuple[list[float], list[float]]:
    torques, angles = [], []
    for _ in range(n):
      if not self.running:
        break
      tq, ang = self._read_state()
      if tq is not None and ang is not None:
        torques.append(tq)
        angles.append(ang)
      time.sleep(SAMPLE_INTERVAL_S)
    return torques, angles

  def _test_step(self, target_angle: float, log_file) -> dict | None:
    print(f"\nCommanding apply_angle = {target_angle:+.1f}°")
    self._write_live_testing(target_angle)
    print("  waiting for driver torque to settle...")
    if not self._wait_for_torque_settle():
      return None

    print(f"  averaging {FINAL_SAMPLE_COUNT} post-settle samples...")
    tq_samples, ang_samples = self._collect_samples(FINAL_SAMPLE_COUNT)
    if len(tq_samples) < 3:
      print(f"  WARNING: too few samples ({len(tq_samples)})")
      return None

    mean_tq = statistics.mean(tq_samples)
    std_tq = statistics.stdev(tq_samples)
    mean_ang = statistics.mean(ang_samples)
    gap = target_angle - mean_ang

    ts = time.time()
    for i, (tq, ang) in enumerate(zip(tq_samples, ang_samples)):
      log_file.write(f"{ts},{target_angle:.3f},{ang:.3f},{tq:.3f},{i}\n")
    log_file.flush()

    print(f"  target={target_angle:+.1f}°  actual={mean_ang:+.2f}°  "
          f"gap={gap:+.2f}°  tq={mean_tq:+.2f} Nm  (std {std_tq:.2f})")
    return {"target": target_angle, "actual": mean_ang, "gap": gap,
            "torque": mean_tq, "torque_std": std_tq}

  def connect(self) -> bool:
    print("Connecting to carState...")
    self.sm = messaging.SubMaster(['carState'])
    for _ in range(50):
      self.sm.update(timeout=100)
      if self.sm.updated['carState']:
        cs = self.sm['carState']
        print(f"Connected. Initial angle={cs.steeringAngleDeg:+.1f}°, "
              f"torque={cs.steeringTorque:+.2f} Nm")
        return True
      time.sleep(0.1)
    print("ERROR: No carState messages. Is openpilot running?")
    return False

  def run(self) -> None:
    if not self.connect():
      return

    print()
    print("=" * 60)
    print("Torque vs. Angle — driver-torque proportionality test")
    print("=" * 60)
    print(f"Steps (deg): {self.steps}")
    print()
    print("Reminder: hold the wheel FIRMLY at its resting position.")
    print("Do not let it move. Ctrl-C aborts safely.")
    print()
    input("Press ENTER to start... ")

    with open(LOG_FILE, 'w') as log:
      log.write("timestamp,target_angle,actual_angle,driver_torque,sample_num\n")

      for i, step in enumerate(self.steps):
        if not self.running:
          break
        print(f"\n[{i + 1}/{len(self.steps)}]")
        result = self._test_step(step, log)
        if result is not None:
          self.results.append(result)

    print("\nReturning to neutral (apply_angle = 0)...")
    self._write_live_testing(0.0)
    time.sleep(2.0)
    self._disable_live_testing()

    self._analyze()

  def _analyze(self) -> None:
    if len(self.results) < 3:
      print("\nERROR: not enough data for regression.")
      return

    print("\n" + "=" * 60)
    print("RESULTS")
    print("=" * 60)
    print()
    print(f"{'target°':>10} {'actual°':>10} {'gap°':>8} {'tq_Nm':>10} {'std_Nm':>8}")
    print("-" * 50)
    for r in self.results:
      print(f"{r['target']:>+10.1f} {r['actual']:>+10.2f} {r['gap']:>+8.2f} "
            f"{r['torque']:>+10.2f} {r['torque_std']:>8.2f}")

    gaps = [r['gap'] for r in self.results]
    torques = [r['torque'] for r in self.results]

    mg = statistics.mean(gaps)
    mt = statistics.mean(torques)
    num = sum((g - mg) * (t - mt) for g, t in zip(gaps, torques))
    den = sum((g - mg) ** 2 for g in gaps)
    if abs(den) < 1e-10:
      print("\nERROR: all gap values equal; cannot fit.")
      return

    k = num / den
    b = mt - k * mg
    ss_res = sum((t - (k * g + b)) ** 2 for g, t in zip(gaps, torques))
    ss_tot = sum((t - mt) ** 2 for t in torques)
    r_sq = 1 - ss_res / ss_tot if ss_tot > 1e-10 else 0.0

    print("\nLinear fit: torque = k * gap + b")
    print(f"  k = {k:+.3f} Nm per 1° of gap")
    print(f"  b = {b:+.3f} Nm (intercept; should be near 0)")
    print(f"  R² = {r_sq:.4f}  (1.0 = perfect line; <0.9 = noisy or non-linear)")
    print()
    if r_sq > 0.9:
      print("  → Hypothesis confirmed: driver torque IS ~linear in gap.")
      print(f"  → A MAX_ERR_DEG cap at N° bounds driver fight-torque to ~{abs(k):.1f}·N Nm.")
    else:
      print("  → Linear fit is poor. Relationship may be non-linear, or data is noisy.")
      print("  → Check the CSV log for per-sample values.")
    print(f"\nLog saved to: {LOG_FILE}")


def main() -> None:
  parser = argparse.ArgumentParser(description=__doc__.splitlines()[1] if __doc__ else None)
  parser.add_argument(
    "--steps", type=float, nargs="*",
    default=[0.0, 5.0, 10.0, 15.0, 25.0, 15.0, 10.0, 5.0, 0.0,
             -5.0, -10.0, -15.0, -25.0, -15.0, -10.0, -5.0, 0.0],
    help="apply_angle sequence in degrees (default: symmetric ±25° sweep)",
  )
  args = parser.parse_args()

  print("=" * 60)
  print("Volvo CMA — torque-vs-angle calibration")
  print("=" * 60)
  print()
  print("SAFETY CHECKLIST:")
  print("  [ ] Vehicle STATIONARY, brake firmly pressed, gear in P or N")
  print("  [ ] Openpilot engaged with lateral active")
  print("  [ ] Wheel free of obstructions; no one else in the car nearby")
  print("  [ ] You can hold the wheel firmly for the full test duration")
  print(f"  [ ] You will stop if driver torque exceeds {MAX_DRIVER_TORQUE_NM} Nm")
  print()
  input("Press ENTER when all items are confirmed (Ctrl-C to abort)... ")

  TorqueVsAngleCalibrator(args.steps).run()


if __name__ == "__main__":
  main()
