#!/usr/bin/env python3
"""
Test script to investigate whether NEW_SIGNAL_4 in LCA (0x58) controls steering rate of change.

Theory: Stock LCA uses NEW_SIGNAL_4=39 when active (observed increasing from 35 to 39 when
the PSCM couldn't meet the requested angle fast enough). This suggests it may be a steering
authority/rate parameter.

Method:
  1. Command a fixed angle step (e.g., 0 -> 15 degrees)
  2. Vary NEW_SIGNAL_4 across test values (stock=39, then 50, 80, 120, etc.)
  3. Measure how fast the steering angle reaches the target
  4. Compare rate-of-change profiles across NEW_SIGNAL_4 values

Usage:
  python test_lca_new_signal_4.py                    # Default test
  python test_lca_new_signal_4.py --angle 10         # Custom step angle
  python test_lca_new_signal_4.py --values 39,60,80  # Custom NEW_SIGNAL_4 values
  python test_lca_new_signal_4.py --repeat 3         # Repeat each test 3 times

Requirements:
  - openpilot must be running (carState must be published)
  - Car should be stationary or moving slowly
  - Steering must be free to move (not held by driver)
"""

import sys
import time
import signal
import argparse
import statistics
from pathlib import Path

# Add openpilot to path if needed
OPENPILOT_PATH = Path(__file__).resolve().parents[5]
if str(OPENPILOT_PATH) not in sys.path:
  sys.path.insert(0, str(OPENPILOT_PATH))

import cereal.messaging as messaging

# Configuration
LIVE_TESTING_FILE = "/data/openpilot/live_testing.txt"
LOG_FILE = "/data/openpilot/lca_new_signal_4_test.csv"

# Timing
SAMPLE_INTERVAL_S = 0.02    # 50 Hz sampling (20ms)
NEUTRAL_SETTLE_S = 3.0      # Time to settle at neutral before each test
RECORD_DURATION_S = 4.0     # How long to record after commanding the step
SETTLE_THRESHOLD_DEG = 0.3  # Angle must be stable within this range
SETTLE_WINDOW = 15           # Number of samples for settle detection

# Safety
MAX_ANGLE_DEG = 40.0
DEFAULT_STEP_ANGLE = 15.0

# Stock value for reference
STOCK_NEW_SIGNAL_4 = 39
DEFAULT_TEST_VALUES = [39, 50, 70, 100, 130, 170, 200, 251]


class RateOfChangeTester:
  def __init__(self, step_angle: float, test_values: list[int], repeats: int, max_angle: float):
    self.step_angle = step_angle
    self.test_values = test_values
    self.repeats = repeats
    self.max_angle = max_angle
    self.running = True
    self.sm = None
    self.all_results = {}  # {ns4_value: [list of trial results]}

    signal.signal(signal.SIGINT, self._signal_handler)
    signal.signal(signal.SIGTERM, self._signal_handler)

  def _signal_handler(self, sig, frame):
    print("\nInterrupted, cleaning up...")
    self.running = False
    self._disable_live_testing()
    sys.exit(0)

  def _write_live_testing(self, lat_active: bool, apply_angle: float | None = None,
                          new_signal_4: int | None = None):
    """Write test configuration to live_testing.txt"""
    lines = ["# Auto-generated by test_lca_new_signal_4.py"]

    if not lat_active:
      lines.append("lat_active=False")
    else:
      lines.append("lat_active=True")
      if apply_angle is not None:
        lines.append(f"apply_angle={apply_angle}")
      if new_signal_4 is not None:
        lines.append(f"lca.new_signal_4={new_signal_4}")

    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write('\n'.join(lines) + '\n')

  def _disable_live_testing(self):
    """Disable live testing"""
    with open(LIVE_TESTING_FILE, 'w') as f:
      f.write("# Auto-generated\nlat_active=False\n")
    print("Live testing disabled")

  def _get_angle(self) -> float | None:
    """Get current steering angle from carState"""
    self.sm.update(timeout=1000)
    if self.sm.updated['carState']:
      return self.sm['carState'].steeringAngleDeg
    return None

  def _wait_for_settle(self, target: float | None = None) -> bool:
    """Wait until steering angle stabilizes near target"""
    recent_angles = []
    start_time = time.time()
    timeout = NEUTRAL_SETTLE_S + 2.0

    while self.running:
      if time.time() - start_time > timeout:
        if recent_angles:
          avg = statistics.mean(recent_angles[-SETTLE_WINDOW:])
          print(f"  Settle timeout (current: {avg:.2f}°)")
        return True  # Proceed anyway after timeout

      angle = self._get_angle()
      if angle is None:
        continue

      # Safety check
      if abs(angle) > self.max_angle:
        print(f"  SAFETY: Angle {angle:.1f}° exceeds limit!")
        return False

      recent_angles.append(angle)
      if len(recent_angles) > SETTLE_WINDOW:
        recent_angles.pop(0)

      if len(recent_angles) >= SETTLE_WINDOW:
        angle_range = max(recent_angles) - min(recent_angles)
        if angle_range < SETTLE_THRESHOLD_DEG:
          return True

      time.sleep(SAMPLE_INTERVAL_S)

    return False

  def _record_step_response(self, new_signal_4: int, log_file) -> dict | None:
    """
    Record a single step response:
    1. Command neutral (0°) and wait for settle
    2. Command step_angle with given NEW_SIGNAL_4
    3. Record angle samples at 50 Hz for RECORD_DURATION_S
    4. Return to neutral

    Returns dict with timing/rate metrics, or None on failure.
    """
    # Phase 1: Go to neutral
    print(f"    Returning to neutral...")
    self._write_live_testing(True, apply_angle=0.0, new_signal_4=STOCK_NEW_SIGNAL_4)
    if not self._wait_for_settle(target=0.0):
      return None
    time.sleep(NEUTRAL_SETTLE_S)

    initial_angle = self._get_angle()
    if initial_angle is None:
      return None

    # Phase 2: Command step with test NEW_SIGNAL_4 value
    print(f"    Commanding {self.step_angle}° with NEW_SIGNAL_4={new_signal_4}...")
    step_time = time.monotonic()
    self._write_live_testing(True, apply_angle=self.step_angle, new_signal_4=new_signal_4)

    # Phase 3: Record at 50 Hz
    samples = []  # (elapsed_s, angle_deg)
    record_start = time.monotonic()

    while self.running:
      now = time.monotonic()
      elapsed = now - step_time
      if elapsed > RECORD_DURATION_S:
        break

      angle = self._get_angle()
      if angle is not None:
        samples.append((elapsed, angle))

        # Safety check
        if abs(angle) > self.max_angle:
          print(f"    SAFETY: Angle {angle:.1f}° exceeds limit!")
          self._write_live_testing(True, apply_angle=0.0, new_signal_4=STOCK_NEW_SIGNAL_4)
          return None

      time.sleep(SAMPLE_INTERVAL_S)

    if len(samples) < 10:
      print(f"    WARNING: Only {len(samples)} samples collected")
      return None

    # Write samples to CSV
    for elapsed, angle in samples:
      log_file.write(f"{new_signal_4},{elapsed:.4f},{angle:.4f},{self.step_angle},{initial_angle:.4f}\n")
    log_file.flush()

    # Analyze the step response
    return self._analyze_step(samples, initial_angle)

  def _analyze_step(self, samples: list[tuple[float, float]], initial_angle: float) -> dict:
    """Compute rate-of-change metrics from a step response."""
    target = self.step_angle
    threshold_90 = initial_angle + 0.9 * (target - initial_angle)
    threshold_63 = initial_angle + 0.63 * (target - initial_angle)  # time constant

    # Find time to reach 63% and 90% of target
    time_to_63 = None
    time_to_90 = None
    for elapsed, angle in samples:
      if time_to_63 is None and angle >= threshold_63:
        time_to_63 = elapsed
      if time_to_90 is None and angle >= threshold_90:
        time_to_90 = elapsed

    # Compute max rate of change (deg/s) using sliding window
    max_rate = 0.0
    window = 5  # 5 samples at 50Hz = 100ms window
    for i in range(window, len(samples)):
      dt = samples[i][0] - samples[i - window][0]
      if dt > 0:
        rate = abs(samples[i][1] - samples[i - window][1]) / dt
        max_rate = max(max_rate, rate)

    # Final angle (average of last 20 samples)
    final_angles = [a for _, a in samples[-20:]]
    final_angle = statistics.mean(final_angles) if final_angles else samples[-1][1]

    return {
      'initial_angle': initial_angle,
      'final_angle': final_angle,
      'time_to_63pct': time_to_63,
      'time_to_90pct': time_to_90,
      'max_rate_deg_s': max_rate,
      'n_samples': len(samples),
    }

  def connect(self) -> bool:
    """Connect to carState"""
    print("Connecting to carState...")
    self.sm = messaging.SubMaster(['carState'])

    print("Waiting for messages...")
    for _ in range(50):
      self.sm.update(timeout=100)
      if self.sm.updated['carState']:
        angle = self.sm['carState'].steeringAngleDeg
        print(f"Connected! Current angle: {angle:.2f}°")
        return True
      time.sleep(0.1)

    print("ERROR: No carState messages. Is openpilot running?")
    return False

  def run(self):
    if not self.connect():
      return

    print(f"\n{'='*65}")
    print("LCA NEW_SIGNAL_4 Rate-of-Change Test")
    print(f"{'='*65}")
    print(f"Step angle:       0° -> {self.step_angle}°")
    print(f"Test values:      {self.test_values}")
    print(f"Repeats per value: {self.repeats}")
    print(f"Sample rate:      {1/SAMPLE_INTERVAL_S:.0f} Hz")
    print(f"Record duration:  {RECORD_DURATION_S}s per step")
    print(f"Safety limit:     ±{self.max_angle}°")
    print(f"Log file:         {LOG_FILE}")
    print()
    print("Stock NEW_SIGNAL_4 = 39 (baseline)")
    print("Hypothesis: Higher values = faster steering rate")
    print()

    with open(LOG_FILE, 'w') as log:
      log.write("new_signal_4,elapsed_s,angle_deg,target_deg,initial_deg\n")

      for ns4_val in self.test_values:
        if not self.running:
          break

        self.all_results[ns4_val] = []

        for trial in range(self.repeats):
          if not self.running:
            break

          print(f"\n[NEW_SIGNAL_4={ns4_val}] Trial {trial+1}/{self.repeats}")
          result = self._record_step_response(ns4_val, log)

          if result:
            self.all_results[ns4_val].append(result)
            t63 = f"{result['time_to_63pct']:.3f}s" if result['time_to_63pct'] else "N/A"
            t90 = f"{result['time_to_90pct']:.3f}s" if result['time_to_90pct'] else "N/A"
            print(f"    -> max_rate={result['max_rate_deg_s']:.1f}°/s, "
                  f"t63={t63}, t90={t90}, final={result['final_angle']:.2f}°")
          else:
            print(f"    -> FAILED")

    # Return to neutral and disable
    print("\nReturning to neutral...")
    self._write_live_testing(True, apply_angle=0.0, new_signal_4=STOCK_NEW_SIGNAL_4)
    time.sleep(2.0)
    self._disable_live_testing()

    self._print_summary()

  def _print_summary(self):
    """Print comparison table across all NEW_SIGNAL_4 values"""
    print(f"\n{'='*65}")
    print("SUMMARY: NEW_SIGNAL_4 vs Steering Rate of Change")
    print(f"{'='*65}")
    print(f"Step: 0° -> {self.step_angle}°")
    print()

    header = f"{'NS4':>5} {'MaxRate(°/s)':>13} {'t63(s)':>8} {'t90(s)':>8} {'Final(°)':>9} {'Trials':>7}"
    print(header)
    print("-" * len(header))

    for ns4_val in self.test_values:
      trials = self.all_results.get(ns4_val, [])
      if not trials:
        print(f"{ns4_val:>5} {'FAILED':>13}")
        continue

      rates = [t['max_rate_deg_s'] for t in trials]
      t63s = [t['time_to_63pct'] for t in trials if t['time_to_63pct'] is not None]
      t90s = [t['time_to_90pct'] for t in trials if t['time_to_90pct'] is not None]
      finals = [t['final_angle'] for t in trials]

      avg_rate = statistics.mean(rates)
      avg_t63 = statistics.mean(t63s) if t63s else None
      avg_t90 = statistics.mean(t90s) if t90s else None
      avg_final = statistics.mean(finals)

      t63_str = f"{avg_t63:.3f}" if avg_t63 else "N/A"
      t90_str = f"{avg_t90:.3f}" if avg_t90 else "N/A"

      marker = " <-- stock" if ns4_val == STOCK_NEW_SIGNAL_4 else ""
      print(f"{ns4_val:>5} {avg_rate:>13.1f} {t63_str:>8} {t90_str:>8} {avg_final:>9.2f} {len(trials):>7}{marker}")

    # Verdict
    stock_trials = self.all_results.get(STOCK_NEW_SIGNAL_4, [])
    if stock_trials:
      stock_rate = statistics.mean([t['max_rate_deg_s'] for t in stock_trials])

      faster = []
      for ns4_val in self.test_values:
        if ns4_val == STOCK_NEW_SIGNAL_4:
          continue
        trials = self.all_results.get(ns4_val, [])
        if trials:
          rate = statistics.mean([t['max_rate_deg_s'] for t in trials])
          if rate > stock_rate * 1.1:  # 10% faster threshold
            faster.append((ns4_val, rate))

      print()
      if faster:
        print("RESULT: NEW_SIGNAL_4 DOES affect steering rate!")
        print(f"  Stock rate (NS4={STOCK_NEW_SIGNAL_4}): {stock_rate:.1f}°/s")
        for ns4_val, rate in faster:
          improvement = (rate / stock_rate - 1) * 100
          print(f"  NS4={ns4_val}: {rate:.1f}°/s (+{improvement:.0f}%)")
      else:
        print("RESULT: No significant rate difference detected.")
        print("  NEW_SIGNAL_4 may not control steering rate,")
        print("  or the PSCM ignores it for rate limiting.")

    print(f"\nRaw data saved to: {LOG_FILE}")
    print("Analyze with: plot columns elapsed_s vs angle_deg, grouped by new_signal_4")


def main():
  parser = argparse.ArgumentParser(description='Test if LCA NEW_SIGNAL_4 controls steering rate')
  parser.add_argument('--angle', type=float, default=DEFAULT_STEP_ANGLE,
                      help=f'Step angle in degrees (default: {DEFAULT_STEP_ANGLE}°)')
  parser.add_argument('--values', type=str, default=None,
                      help='Comma-separated NEW_SIGNAL_4 values to test (default: 39,50,70,100,130,170,200,251)')
  parser.add_argument('--repeat', type=int, default=2,
                      help='Number of trials per value (default: 2)')
  parser.add_argument('--max-angle', type=float, default=MAX_ANGLE_DEG,
                      help=f'Safety limit (default: {MAX_ANGLE_DEG}°)')
  args = parser.parse_args()

  if args.values:
    test_values = [int(v.strip()) for v in args.values.split(',')]
  else:
    test_values = DEFAULT_TEST_VALUES

  # Validate
  for v in test_values:
    if v < 0 or v > 255:
      print(f"ERROR: NEW_SIGNAL_4 value {v} out of range (0-255)")
      sys.exit(1)

  print("=" * 65)
  print("LCA NEW_SIGNAL_4 Rate-of-Change Test")
  print("=" * 65)
  print()
  print("IMPORTANT:")
  print("  1. openpilot must be running")
  print("  2. Car should be stationary or moving slowly")
  print("  3. Don't touch the steering wheel")
  print("  4. Be ready to grab the wheel if anything unexpected happens")
  print()
  print(f"Will command steps of {args.angle}° with varying NEW_SIGNAL_4 values.")
  print(f"Stock value is 39 — testing: {test_values}")
  print()
  input("Press Enter to start...")

  tester = RateOfChangeTester(args.angle, test_values, args.repeat, args.max_angle)
  tester.run()


if __name__ == "__main__":
  main()
